on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - uses: "docker/setup-buildx-action@v2"
      - uses: "docker/build-push-action@v4"
        with:
          build-args: |
            ARTIFACTS_TOKEN=${{ secrets.ARTIFACTS_TOKEN }}
            BRANCH=${{ steps.extract_branch.outputs.branch }}
          push: false
